version: '3.8'

services:
  planty:
    image: planty-bot
    env_file:
      - .env
    build: .
    restart: always
    depends_on:
      - sprout
      
  sprout:
    image: sprout
    env_file:
      - .env
    build: ./sprout-img
    ports:
      - "3000:3000"
