name: Build, Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT.ID }}
        TWITCH_AUTHORIZATION: ${{ secrets.TWITCH_AUTHORIZATION }}
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: TWITCH_CLIENT_ID, TWITCH_AUTHENTICATION
        script: |
          export TWITCH_CLIENT_ID="$TWITCH_CLIENT_ID"
          export TWITCH_AUTHORIZATION="$TWITCH_AUTHORIZATION"
          cd projects/planty
          git pull
          docker-compose up --build -d
